// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import controllers from "./**/*_controller.js"

// Import and register all your controllers
// import("./hello_controller").then(c => application.register("hello", c.default))
controllers.forEach((controller) => {
  application.register(controller.name, controller.module.default)
})
